- name: delete picom config directory
  file:
    path: ~/.config/picom
    state: absent
  tags:
    - picom

- name: create picom config directory
  file:
    path: ~/.config/picom
    state: directory
  tags:
    - picom

- name: symlink dotfiles
  file:
    src: "{{ ansible_env.PWD }}/roles/picom/files/{{ item }}"
    path: ~/.config/picom/{{ item }}
    state: link
    follow: false
    force: yes
  loop:
    - picom.conf
  tags:
    - picom
