[icons]
name = "material-nf"

[theme.overrides]
idle_bg = "#362124"
idle_fg = "#848082"
info_bg = "#7B7778"
info_fg = "#fafafa"
good_bg = "auto"
good_fg = "auto"
warning_bg = "#4f393a"
warning_fg = "#878ba6"
critical_bg = "#a05758"
critical_fg = "#e8dadc"
separator = "<span font='15'></span>"
separator_bg = "auto"
separator_fg = "auto"

[[block]]
block = "focused_window"
max_width = 75
show_marks = "visible"

[[block]]
block = "disk_space"
path = "/home"
alias = "/home"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0

[[block]]
block = "disk_space"
path = "/home/Media"
alias = "/home/Media"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%a %m/%d %R"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
dynamic_width = true
hide_when_empty = true
max_width = 30

[[block]]
block = "custom"
command = "whoami"
interval = "once"

[[block]]
block = "custom"
command = "cat /etc/hostname"
interval = "once"

[[block]]
block = "custom"
command = "echo `uname` `uname -r | tr - . | cut -d. -f1-2`"
interval = "once"
