- name: apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags:
    - apt
    - apt-update

- name: apt-get upgrade
  apt:
    upgrade: dist
  become: yes
  tags:
    - apt
    - apt-upgrade

- name: make sure packages are installed
  become: yes
  package:
    name:
      - curl
      - git
      - nala
      - dbus-x11
  tags:
    - packages
    - curl
    - git
    - nala
    - dbus-x11
