- name: create alacritty config directory
  file:
    path: ~/.config/alacritty
    state: directory
  tags:
    - alacritty

- name: symlink files
  file:
    src: "{{ ansible_env.PWD }}/roles/alacritty/files/{{ item }}"
    path: "~/.config/alacritty/{{ item }}"
    state: link
    follow: false
    force: yes
  loop:
    - alacritty.yml
    - colors.yml
    - fonts.yml
  tags:
    - alacritty
