- name: install C/C++ development tools
  apt:
    name:
      - clang
      - clang-format
      - make
      - cmake
      - gcc
      - g++
      - gdb
    state: present
  become: yes
  tags:
    - apt
    - languages
    - c
    - c++