- name: install python development tools
  apt:
    name:
      - python3
      - python3-pip
      - python-is-python3
      - python3-venv
  become: yes
  tags:
    - apt
    - languages
    - python

- name: install black to format python code
  pip:
    name: black
    state: present
  become: yes
  tags:
    - pip
    - languages
    - python

- name: install python linters
  pip:
    name:
      - flake8
      - pylint
    state: present
  become: yes
  tags:
    - pip
    - languages
    - python
